# -*- coding: utf-8 -*-
"""NUR_HANAN_BINTI_MOHAMMAD_ZAMRI_25013519_W4_ASSIGNMENT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m49Q8JfqH1I0wF71ZIX0Be5pu1Y9az-L

ASSIGNMENT WEEK 4
NAME: NUR HANAN BINTI MOHAMMAD ZAMRI
STUDENT ID:25013519
COURSE NAME: INTRODUCTION TO OPEN SOURCE SOFTWARE
"""

# ─── FUNCTION 1 ────────────────────────────────────────────────
# Welcomes a new developer and shows their role and badge
# badge is a LOCAL variable — only available inside this function
def welcome_developer(name, role):
  badge = role.upper()
  print("==========================================")
  print(f"Welcome {name} to MediaWiki")
  print(f"Role: {role}")
  print(f"Badge: {badge}")
  print("==========================================")

# ─── FUNCTION 2 ────────────────────────────────────────────────
# Assigns a development task based on the developer role
# project has a DEFAULT VALUE of 'MediaWiki'
# This function must RETURN the task
def assign_task(role, project = 'MediaWiki'):
  match role:
    case 'Junior Developer' :
      task = 'Fix a typo or formatting error in the codebase'
    case 'Active Developer' :
      task = 'Review and test an open pull request'
    case 'Senior Developer' :
      task = 'Fix a reported bug in the software'
    case 'Lead Developer' :
      task = 'Design and lead a new feature development'
    case _:
      task = 'Read the CONTRIBUTING file on GitHub'

  print(f'Project : {project}')
  print(f'Task : {task}')
  return task

# ─── FUNCTION 3 ────────────────────────────────────────────────
# Accepts ANY NUMBER of skills using *skills
# Uses a FOR loop to print each skill
def check_skills(*skills):
  print('Skills registered:')
  for skill in skills:
    print(f' - {skill}')
    print(f'Total skills:{len(skills)}')

# ─── PRINT PROJECT BANNER ──────────────────────────────────────
print('==========================================')
print(' MEDIAWIKI — COMMUNITY MANAGER')
print('==========================================')
print(f'Project : MediaWiki')
print(f'GitHub : github.com/wikimedia/mediawiki')
print(f'Stars : 4,200+')
print(f'Contributors: 1,000+ software developers')
print('==========================================')

# Create an empty list to store names of developers who joined
joined_developers = []

# ─── WHILE LOOP — keep running until user says no ──────────────
while True:
  name = input('Enter developer name : ')
  experience = input('Enter experience level : ')
  # (beginner / intermediate / advanced / expert)
  # Use match statement to assign role based on experience
  match experience:
    case 'beginner' :
      role = 'Junior Developer'
    case 'intermediate' :
      role = 'Active Developer'
    case 'advanced' :
      role = 'Senior Developer'
    case 'expert' :
      role = 'Lead Developer'
    case _:
      role = 'Observer'

  # Call welcome_developer — pass name and role
  welcome_developer(name, role)
  # Call assign_task — pass role only (project uses default value)
  assign_task(role)
  # Add the developer name to joined_developers list
  joined_developers.append(name)

  again = input('Add another developer? (yes/no): ')
  # If user says no — stop the loop
  if again == 'no':
    break

# ─── ADD TEST NAMES BEFORE SCANNING ───────────────────────────
joined_developers.append('Anonymous')
joined_developers.append('Vandal')
joined_developers.append('Sara')

print('------------------------------------------')
print('Scanning developer list...')
print('------------------------------------------')

# ─── FOR LOOP — scan every developer in the list ───────────────
for developer in joined_developers:
# Skip Anonymous — do not verify, move to next developer
  if developer == 'Anonymous':
    print(f'Skipping {developer} — anonymous not allowed')
    continue
# Stop scan — Vandal should not be in the project
  if developer == 'Vandal':
    print('WARNING: Vandal detected! Stopping scan.')
    break

  print(f'Developer verified: {developer}')

# ─── FOR LOOP OVER STRING ───────────────────────────────────────
# Loop over each character in the string 'MediaWiki'
print('------------------------------------------')
print('Project name characters:')
for character in 'MediaWiki':
  print(character)

# ─── FUNCTION 4 ────────────────────────────────────────────────
# Generates the final community report
# Accepts project name + ANY NUMBER of developer names via *developers
def generate_report(project, *developers):
  print('==========================================')
  print(' MEDIAWIKI COMMUNITY REPORT')
  print('==========================================')
  print(f' Project : {project}')
  print(f' Total : {len(joined_developers)} developers joined')
  print('------------------------------------------')
  print(' Developer List:')
  for developer in developers:
    print(f' - {developer}')

  print('==========================================')

# ─── CALL generate_report ───────────────────────────────────────
# Use * to unpack joined_developers list when calling the function
generate_report('MediaWiki', *joined_developers)
# ─── CALL check_skills ──────────────────────────────────────────
# Call the function from Part 1 with three real MediaWiki skills
check_skills('PHP', 'JavaScript', 'MediaWiki API')

import sys

print("Python version: ",sys.version)
print("Platform: ", sys.platform)
print("Environment: Google Colab")

